---
os: linux
dist: bionic
language: ruby
rvm:
  - 2.6.5

addons:
  apt_packages: libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

script:
  - bundle exec rake test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
